title: "[QUESTION] "
labels: ["Questions and Help"]

body:
  - type: markdown
    attributes:
      value: |
        ### Please provide us with the following information to best help you. To get the best help, please be as descriptive as possible. Be sure to use good [question asking best practice](https://xyproblem.info/).
  - type: input
    id: story
    attributes:
      label: Story
      description: "Are you working on a specific story? Please provide the name of the story below."
      value: |
        Story: Create Form Entry Page
    validations:
      required: true
  - type: textarea
    id: solving
    attributes:
      label: What are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What do you expect to happen?
    validations:
      required: true
  - type: textarea
    id: observations
    attributes:
      label: What is happening from your observations?
    validations:
      required: false
  - type: textarea
    id: trouble
    attributes:
      label: What is the trouble you are encountering?
    validations:
      required: false
  - type: textarea
    id: tried
    attributes:
      label: What have you tried so far?
    validations:
      required: true      